CREATE table book
(Book_ID INT NOT NULL,
Book_Name VARCHAR(30) NOT NULL,
Catogories CHAR(20) NOT NULL,
Book_Price  DECIMAL(4,2) NOT NULL,
Book_Pub_Date DATE NOT NULL,
Pub_ID INT NOT NULL,
CONSTRAINT PK PRIMARY KEY (Book_ID),
CONSTRAINT FK FOREIGN KEY (Pub_ID) REFERENCES publisher (Pub_ID))