CREATE table book_publisher
(Book_ID INT NOT NULL,
Pub_ID INT NOT NULL,
Month CHAR(20) NOT NULL,
Quantity INT NOT NULL,
Inv_Num INT NOT NULL,
constraint PK PRIMARY KEY(Book_ID,Pub_ID,Inv_Num),
constraint FK4 FOREIGN KEY (Book_ID) REFERENCES book (Book_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
constraint FK5 FOREIGN KEY (Pub_ID) REFERENCES publisher (Pub_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
constraint FK9 FOREIGN KEY (Inv_Num) REFERENCES invoice (Inv_Num)
ON DELETE CASCADE
ON UPDATE CASCADE)