CREATE table order_
(Order_ID INT NOT NULL,
Order_Date DATE NOT NULL,
Cus_ID INT NOT NULL,
StatusOfDelivery CHAR(30) NOT NULL,
CONSTRAINT PK PRIMARY KEY (Order_ID),
CONSTRAINT FK3 FOREIGN KEY (Cus_ID) REFERENCES customer (Cus_ID))